
name: deploy_gcloud_function
on:
  workflow_dispatch:

jobs:
  deploy_google_cloud:
    runs-on: ubuntu-latest
    
    env:
      # these need to be updated to suit the configuration
      WORKLOAD_ID_PROVIDER: 'projects/719891393859/locations/global/workloadIdentityPools/github-pool-02/providers/github-token-provider-02'
      PROJECT_ID: mp-indents-01
      SERVICE_ACCOUNT_NAME: github-service-02
      VERSION_FILE: src/python-version.txt
      REQUIREMENTS_FILE: src/requirements.txt

    permissions:
      contents: read
      id-token: write

    steps:
    - id: checkout
      uses: actions/checkout@v3
    
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version-file: ${{ env.VERSION_FILE }}
        cache: 'pip'
    
    - name: install dependencies
      run: |
        pip3 install -r "$REQUIREMENTS_FILE"
    
    - id: authenticate
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: '${{ env.WORKLOAD_ID_PROVIDER }}'
        service_account: '${{ env.SERVICE_ACCOUNT_NAME }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

    - name: 'configure-gcloud'
      run: |-
        gcloud config set project "${PROJECT_ID}"
